import '@/ai/flows/generate-product-recommendations.ts';
import '@/ai/flows/generate-style-recommendation.ts';
import '@/ai/flows/find-similar-products.ts';
import '@/ai/flows/virtual-try-on.ts';
import '@/ai/flows/generate-graphic-design.ts';
import '@/ai/flows/generate-product-description.ts';
import '@/ai/flows/suggest-product-price.ts';
import '@/ai/flows/generate-admin-report.ts';
import '@/ai/flows/suggest-supplier.ts';
